In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
weather = pd.read_csv("weatherAUS.csv")

In [3]:
weather.head(3)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No

In [4]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null object
RISK_MM          142193 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(17), object(7)
memory usage: 26.0+ MB

In [5]:
weather.describe(include = 'all')

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
count,142193,142193,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132863,132923.000000,132180,...,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,140787,142193.000000,142193
unique,3436,49,NaN,NaN,NaN,NaN,NaN,16,NaN,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2
top,2014-07-21,Canberra,NaN,NaN,NaN,NaN,NaN,W,NaN,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No
freq,49,3418,NaN,NaN,NaN,NaN,NaN,9780,NaN,11393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109332,NaN,110316
mean,NaN,NaN,12.186400,23.226784,2.349974,5.469824,7.624853,NaN,39.984292,NaN,...,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,NaN,2.360682,NaN
std,NaN,NaN,6.403283,7.117618,8.465173,4.188537,3.781525,NaN,13.588801,NaN,...,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,NaN,8.477969,NaN
min,NaN,NaN,-8.500000,-4.800000,0.000000,0.000000,0.000000,NaN,6.000000,NaN,...,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,NaN,0.000000,NaN
25%,NaN,NaN,7.600000,17.900000,0.000000,2.600000,4.900000,NaN,31.000000,NaN,...,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,NaN,0.000000,NaN
50%,NaN,NaN,12.000000,22.600000,0.000000,4.800000,8.500000,NaN,39.000000,NaN,...,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,NaN,0.000000,NaN
75%,NaN,NaN,16.800000,28.200000,0.800000,7.400000,10.600000,NaN,48.000000,NaN,...,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,NaN,0.800000,NaN
max,NaN,NaN,33.900000,48.100000,371.000000,145.000000,14.500000,NaN,135.000000,NaN,...,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,NaN,371.000000,NaN

In [6]:
print(weather.std())

MinTemp           6.403283
MaxTemp           7.117618
Rainfall          8.465173
Evaporation       4.188537
Sunshine          3.781525
WindGustSpeed    13.588801
WindSpeed9am      8.893337
WindSpeed3pm      8.803345
Humidity9am      19.051293
Humidity3pm      20.797772
Pressure9am       7.105476
Pressure3pm       7.036677
Cloud9am          2.887016
Cloud3pm          2.720633
Temp9am           6.492838
Temp3pm           6.937594
RISK_MM           8.477969
dtype: float64

In [7]:
weather.index

RangeIndex(start=0, stop=142193, step=1)

In [8]:
weather.tail(n=5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,0.0,No
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0.0,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0.0,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0.0,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,0.0,No

In [9]:
weather.columns

Index([u'Date', u'Location', u'MinTemp', u'MaxTemp', u'Rainfall',
       u'Evaporation', u'Sunshine', u'WindGustDir', u'WindGustSpeed',
       u'WindDir9am', u'WindDir3pm', u'WindSpeed9am', u'WindSpeed3pm',
       u'Humidity9am', u'Humidity3pm', u'Pressure9am', u'Pressure3pm',
       u'Cloud9am', u'Cloud3pm', u'Temp9am', u'Temp3pm', u'RainToday',
       u'RISK_MM', u'RainTomorrow'],
      dtype='object')

In [10]:
weather.shape

(142193, 24)

In [11]:
weather.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [12]:
weather.columns.values

array(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am',
       'WindDir3pm', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'], dtype=object)

In [14]:
weather['Date']

0         2008-12-01
1         2008-12-02
2         2008-12-03
3         2008-12-04
4         2008-12-05
5         2008-12-06
6         2008-12-07
7         2008-12-08
8         2008-12-09
9         2008-12-10
10        2008-12-11
11        2008-12-12
12        2008-12-13
13        2008-12-14
14        2008-12-16
15        2008-12-17
16        2008-12-18
17        2008-12-19
18        2008-12-20
19        2008-12-21
20        2008-12-22
21        2008-12-23
22        2008-12-24
23        2008-12-25
24        2008-12-26
25        2008-12-27
26        2008-12-28
27        2008-12-29
28        2008-12-30
29        2008-12-31
             ...
142163    2017-05-26
142164    2017-05-27
142165    2017-05-28
142166    2017-05-29
142167    2017-05-30
142168    2017-05-31
142169    2017-06-01
142170    2017-06-02
142171    2017-06-03
142172    2017-06-04
142173    2017-06-05
142174    2017-06-06
142175    2017-06-07
142176    2017-06-08
142177    2017-06-09
142178    2017-06-10
142179    2017-06-11
142180    2017-06-12
142181    2017-06-13
142182    2017-06-14
142183    2017-06-15
142184    2017-06-16
142185    2017-06-17
142186    2017-06-18
142187    2017-06-19
142188    2017-06-20
142189    2017-06-21
142190    2017-06-22
142191    2017-06-23
142192    2017-06-24
Name: Date, Length: 142193, dtype: object

In [16]:
weather.sort_index(axis=1,ascending=False)

,WindSpeed9am,WindSpeed3pm,WindGustSpeed,WindGustDir,WindDir9am,WindDir3pm,Temp9am,Temp3pm,Sunshine,Rainfall,...,Pressure3pm,MinTemp,MaxTemp,Location,Humidity9am,Humidity3pm,Evaporation,Date,Cloud9am,Cloud3pm
0,20.0,24.0,44.0,W,W,WNW,16.9,21.8,NaN,0.6,...,1007.1,13.4,22.9,Albury,71.0,22.0,NaN,2008-12-01,8.0,NaN
1,4.0,22.0,44.0,WNW,NNW,WSW,17.2,24.3,NaN,0.0,...,1007.8,7.4,25.1,Albury,44.0,25.0,NaN,2008-12-02,NaN,NaN
2,19.0,26.0,46.0,WSW,W,WSW,21.0,23.2,NaN,0.0,...,1008.7,12.9,25.7,Albury,38.0,30.0,NaN,2008-12-03,NaN,2.0
3,11.0,9.0,24.0,NE,SE,E,18.1,26.5,NaN,0.0,...,1012.8,9.2,28.0,Albury,45.0,16.0,NaN,2008-12-04,NaN,NaN
4,7.0,20.0,41.0,W,ENE,NW,17.8,29.7,NaN,1.0,...,1006.0,17.5,32.3,Albury,82.0,33.0,NaN,2008-12-05,7.0,8.0
5,19.0,24.0,56.0,WNW,W,W,20.6,28.9,NaN,0.2,...,1005.4,14.6,29.7,Albury,55.0,23.0,NaN,2008-12-06,NaN,NaN
6,20.0,24.0,50.0,W,SW,W,18.1,24.6,NaN,0.0,...,1008.2,14.3,25.0,Albury,49.0,19.0,NaN,2008-12-07,1.0,NaN
7,6.0,17.0,35.0,W,SSE,W,16.3,25.5,NaN,0.0,...,1010.1,7.7,26.7,Albury,48.0,19.0,NaN,2008-12-08,NaN,NaN
8,7.0,28.0,80.0,NNW,SE,NW,18.3,30.2,NaN,0.0,...,1003.6,9.7,31.9,Albury,42.0,9.0,NaN,2008-12-09,NaN,NaN
9,15.0,11.0,28.0,W,S,SSE,20.1,28.2,NaN,1.4,...,1005.7,13.1,30.1,Albury,58.0,27.0,NaN,2008-12-10,NaN,NaN
10,17.0,6.0,30.0,N,SSE,ESE,20.4,28.8,NaN,0.0,...,1008.7,13.4,30.4,Albury,48.0,22.0,NaN,2008-12-11,NaN,NaN
11,15.0,13.0,31.0,NNE,NE,ENE,15.9,17.0,NaN,2.2,...,1004.2,15.9,21.7,Albury,89.0,91.0,NaN,2008-12-12,8.0,8.0
12,28.0,28.0,61.0,W,NNW,NNW,17.4,15.8,NaN,15.6,...,993.0,15.9,18.6,Albury,76.0,93.0,NaN,2008-12-13,8.0,8.0
13,24.0,20.0,44.0,SW,W,SSW,15.8,19.8,NaN,3.6,...,1001.8,12.6,21.0,Albury,65.0,43.0,NaN,2008-12-14,NaN,7.0
14,NaN,22.0,50.0,WNW,NaN,WNW,17.3,26.2,NaN,NaN,...,1010.3,9.8,27.7,Albury,50.0,28.0,NaN,2008-12-16,0.0,NaN
15,11.0,9.0,22.0,ENE,SSW,E,17.2,18.1,NaN,0.0,...,1010.4,14.1,20.9,Albury,69.0,82.0,NaN,2008-12-17,8.0,1.0
16,6.0,20.0,63.0,W,N,WNW,18.0,21.5,NaN,16.8,...,1002.2,13.5,22.9,Albury,80.0,65.0,NaN,2008-12-18,8.0,1.0
17,24.0,17.0,43.0,SSE,WSW,SW,15.5,21.0,NaN,10.6,...,1009.7,11.2,22.5,Albury,47.0,32.0,NaN,2008-12-19,NaN,2.0
18,17.0,6.0,26.0,SSE,SE,NNW,15.8,23.2,NaN,0.0,...,1017.1,9.8,25.6,Albury,45.0,26.0,NaN,2008-12-20,NaN,NaN
19,9.0,9.0,24.0,S,SE,SE,19.1,27.3,NaN,0.0,...,1014.8,11.5,29.3,Albury,56.0,28.0,NaN,2008-12-21,NaN,NaN
20,17.0,22.0,43.0,NE,NE,N,24.5,31.6,NaN,0.0,...,1008.1,17.1,33.0,Albury,38.0,28.0,NaN,2008-12-22,NaN,1.0
21,19.0,20.0,41.0,WNW,W,W,23.8,30.8,NaN,0.0,...,1005.7,20.5,31.8,Albury,54.0,24.0,NaN,2008-12-23,NaN,NaN
22,6.0,13.0,33.0,N,ESE,NW,20.9,29.0,NaN,0.0,...,1008.2,15.3,30.9,Albury,55.0,23.0,NaN,2008-12-24,5.0,NaN
23,4.0,19.0,43.0,W,E,W,21.5,31.2,NaN,0.0,...,1010.1,12.6,32.4,Albury,49.0,17.0,NaN,2008-12-25,NaN,NaN
24,9.0,13.0,35.0,WSW,SE,WSW,23.2,33.0,NaN,0.0,...,1007.6,16.2,33.9,Albury,45.0,19.0,NaN,2008-12-26,NaN,1.0
25,0.0,26.0,57.0,WSW,NaN,W,26.6,31.2,NaN,0.0,...,1003.6,16.9,33.0,Albury,41.0,28.0,NaN,2008-12-27,NaN,1.0
26,13.0,30.0,48.0,WNW,N,WNW,24.6,32.1,NaN,0.0,...,1001.7,20.1,32.7,Albury,56.0,15.0,NaN,2008-12-28,NaN,NaN
27,19.0,30.0,46.0,WNW,NW,WSW,21.6,26.1,NaN,0.0,...,1004.2,19.7,27.2,Albury,49.0,22.0,NaN,2008-12-29,NaN,NaN
28,11.0,22.0,50.0,WNW,WSW,SW,12.5,18.2,NaN,1.2,...,1003.4,12.5,24.2,Albury,78.0,70.0,NaN,2008-12-30,8.0,8.0
29,17.0,17.0,39.0,W,WNW,WNW,16.9,22.7,NaN,0.8,...,1005.1,12.0,24.4,Albury,48.0,28.0,NaN,2008-12-31,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142163,0.0,20.0,39.0,WNW,NaN,NW,16.1,27.2,NaN,0.4,...,1016.1,14.3,27.6,Uluru,68.0,27.0,NaN,2017-05-26,4.0,7.0
142164,6.0,11.0,28.0,W,SSW,WNW,16.6,27.3,NaN,0.0,...,1016.9,9.3,28.0,Uluru,36.0,16.0,NaN,2017-05-27,NaN,NaN
142165,11.0,13.0,33.0,E,SE,ESE,13.8,23.5,NaN,0.0,...,1018.8,8.0,24.6,Uluru,46.0,25.0,NaN,2017-05-28,4.0,NaN
142166,19.0,13.0,37.0,E,E,ESE,13.9,21.0,NaN,0.0,...,1021.7,12.7,22.2,Uluru,59.0,34.0,NaN,2017-05-29,8.0,8.0
142167,13.0,17.0,35.0,E,SE,E,11.8,22.3,NaN,0.0,...,1023.6,9.4,22.7,Uluru,62.0,32.0,NaN,2017-05-30,8.0,4.0
142168,20.0,28.0,46.0,E,E,E,11.1,20.2,NaN,0.0,...,1025.3,5.4,20.5,Uluru,56.0,32.0,NaN,2017-05-31,NaN,NaN
142169,22.0,24.0,43.0,E,E,ESE,9.7,18.3,NaN,0.0,...,1027.1,5.6,19.4,Uluru,61.0,22.0,NaN,2017-06-01,NaN,NaN
142170,17.0,22.0,37.0,E,ESE,ESE,6.8,17.6,NaN,0.0,...,1026.7,1.5,19.2,Uluru,45.0,18.0,NaN,2017-06-02,NaN,NaN
142171,19.0,17.0,39.0,ENE,ESE,E,8.6,18.9,NaN,0.0,...,1024.1,3.8,19.8,Uluru,42.0,22.0,NaN,2017-06-03,NaN,NaN
142172,13.0,15.0,31.0,E,ESE,E,9.5,18.6,NaN,0.0,...,1022.4,4.5,18.8,Uluru,42.0,26.0,NaN,2017-06-04,NaN,NaN
142173,17.0,24.0,37.0,E,ESE,ESE,10.3,19.8,NaN,0.0,...,1023.9,4.9,20.7,Uluru,38.0,11.0,NaN,2017-06-05,NaN,NaN
142174,13.0,28.0,43.0,E,ESE,E,7.9,19.9,NaN,0.0,...,1025.9,1.2,20.8,Uluru,29.0,6.0,NaN,2017-06-06,NaN,NaN
142175,13.0,20.0,43.0,E,ESE,ENE,9.5,20.5,NaN,0.0,...,1025.0,0.5,21.7,Uluru,27.0,19.0,NaN,2017-06-07,NaN,NaN
142176,13.0,26.0,39.0,SE,ESE,ESE,9.1,19.0,NaN,0.0,...,1026.7,4.0,20.0,Uluru,58.0,26.0,NaN,2017-06-08,NaN,NaN
142177,19.0,24.0,43.0,E,ESE,E,8.7,18.9,NaN,0.0,...,1027.7,3.4,19.8,Uluru,54.0,23.0,NaN,2017-06-09,NaN,NaN
142178,15.0,20.0,46.0,E,ESE,E,8.2,17.4,NaN,0.0,...,1027.2,3.2,18.6,Uluru,56.0,29.0,NaN,2017-06-10,NaN,NaN
142179,17.0,17.0,33.0,E,SE,E,8.0,18.8,NaN,0.0,...,1026.2,2.4,19.1,Uluru,59.0,24.0,NaN,2017-06-11,NaN,NaN
142180,13.0,17.0,46.0,E,ESE,E,8.5,19.2,NaN,0.0,...,1025.8,5.1,19.7,Uluru,56.0,29.0,NaN,2017-06-12,NaN,NaN
142181,17.0,19.0,35.0,ENE,ESE,E,10.3,20.3,NaN,0.0,...,1023.0,2.5,21.2,Uluru,57.0,32.0,NaN,2017-06-13,NaN,NaN
142182,11.0,7.0,22.0,SE,SE,SSE,8.9,20.3,NaN,0.0,...,1022.8,2.3,21.4,Uluru,60.0,28.0,NaN,2017-06-14,NaN,NaN
142183,9.0,7.0,19.0,S,S,E,8.8,22.1,NaN,0.0,...,1021.4,2.6,22.5,Uluru,59.0,24.0,NaN,2017-06-15,NaN,NaN
142184,11.0,11.0,24.0,E,SE,E,12.3,23.3,NaN,0.0,...,1020.0,5.2,24.3,Uluru,53.0,24.0,NaN,2017-06-16,NaN,NaN
142185,15.0,17.0,31.0,ESE,S,ESE,11.2,23.1,NaN,0.0,...,1023.0,6.4,23.4,Uluru,53.0,25.0,NaN,2017-06-17,NaN,NaN
142186,19.0,26.0,41.0,ESE,SE,E,11.6,20.0,NaN,0.0,...,1024.3,8.0,20.7,Uluru,56.0,32.0,NaN,2017-06-18,NaN,7.0
142187,15.0,17.0,35.0,E,ESE,E,11.0,20.3,NaN,0.0,...,1023.3,7.4,20.6,Uluru,63.0,33.0,NaN,2017-06-19,NaN,NaN
142188,15.0,13.0,31.0,E,ESE,E,9.4,20.9,NaN,0.0,...,1021.2,3.5,21.8,Uluru,59.0,27.0,NaN,2017-06-20,NaN,NaN
142189,13.0,11.0,31.0,E,SE,ENE,10.1,22.4,NaN,0.0,...,1020.3,2.8,23.4,Uluru,51.0,24.0,NaN,2017-06-21,NaN,NaN
142190,13.0,9.0,22.0,NNW,SE,N,10.9,24.5,NaN,0.0,...,1019.1,3.6,25.3,Uluru,56.0,21.0,NaN,2017-06-22,NaN,NaN
142191,9.0,9.0,37.0,N,SE,WNW,12.5,26.1,NaN,0.0,...,1016.8,5.4,26.9,Uluru,53.0,24.0,NaN,2017-06-23,NaN,NaN
142192,13.0,7.0,28.0,SE,SSE,N,15.1,26.0,NaN,0.0,...,1016.5,7.8,27.0,Uluru,51.0,24.0,NaN,2017-06-24,3.0,2.0

In [17]:
weather.sort_values(by="Location")

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
94847,2011-05-16,Adelaide,5.2,16.6,0.0,3.6,8.8,NE,26.0,NaN,...,44.0,1034.6,1030.6,NaN,NaN,10.6,16.2,No,0.0,No
95911,2014-08-14,Adelaide,9.8,15.5,0.0,2.2,NaN,SE,31.0,E,...,47.0,1035.6,1031.4,NaN,NaN,11.7,14.7,No,0.0,No
95912,2014-08-15,Adelaide,8.5,20.3,0.0,2.0,NaN,E,48.0,WNW,...,40.0,1026.8,1022.9,NaN,NaN,15.0,18.1,No,0.0,No
95913,2014-08-16,Adelaide,10.3,14.0,0.0,NaN,NaN,SE,46.0,SW,...,60.0,1021.6,1019.4,NaN,NaN,10.3,13.0,No,1.8,Yes
95914,2014-08-17,Adelaide,9.4,16.2,1.8,NaN,NaN,SSE,39.0,S,...,73.0,1021.4,1020.5,NaN,NaN,11.6,13.5,Yes,0.0,No
95915,2014-08-18,Adelaide,6.2,14.7,0.0,5.2,NaN,SSE,30.0,W,...,53.0,1024.9,1023.0,NaN,NaN,12.1,14.3,No,0.0,No
95916,2014-08-19,Adelaide,5.3,14.9,0.0,1.6,NaN,S,28.0,ESE,...,48.0,1026.9,1025.1,NaN,NaN,11.4,13.9,No,0.0,No
95917,2014-08-20,Adelaide,6.9,15.1,0.0,1.4,NaN,ESE,30.0,ESE,...,50.0,1027.8,1026.3,NaN,NaN,12.0,13.8,No,0.0,No
95918,2014-08-21,Adelaide,6.1,19.3,0.0,2.2,NaN,E,30.0,ENE,...,39.0,1027.4,1024.0,NaN,NaN,13.8,18.1,No,0.0,No
95919,2014-08-22,Adelaide,12.3,21.1,0.0,2.6,NaN,N,37.0,NNE,...,24.0,1026.7,1022.6,NaN,NaN,17.2,20.5,No,0.0,No
95910,2014-08-13,Adelaide,7.4,13.6,0.0,2.0,NaN,SSE,50.0,ESE,...,45.0,1037.6,1036.0,NaN,NaN,10.6,12.5,No,0.0,No
95920,2014-08-23,Adelaide,15.0,17.9,0.0,NaN,NaN,WNW,41.0,NNW,...,56.0,1023.7,1025.2,NaN,NaN,16.3,16.2,No,0.0,No
95922,2014-08-25,Adelaide,4.2,18.6,0.0,8.0,NaN,WNW,20.0,SSW,...,51.0,1032.3,1028.2,NaN,NaN,11.1,17.1,No,0.0,No
95923,2014-08-26,Adelaide,4.7,19.2,0.0,1.0,NaN,SW,26.0,NaN,...,47.0,1028.2,1024.3,NaN,NaN,12.2,18.8,No,0.0,No
95924,2014-08-27,Adelaide,5.8,22.0,0.0,2.0,NaN,WSW,24.0,NNW,...,41.0,1027.4,1025.7,NaN,NaN,16.2,21.0,No,0.0,No
95925,2014-08-28,Adelaide,7.3,23.5,0.0,2.4,NaN,N,20.0,NNE,...,36.0,1029.3,1026.9,NaN,NaN,14.6,23.0,No,0.0,No
95926,2014-08-29,Adelaide,7.8,24.7,0.0,3.4,NaN,N,20.0,NaN,...,32.0,1028.7,1025.5,NaN,NaN,16.7,23.5,No,0.0,No
95927,2014-08-30,Adelaide,8.5,25.0,0.0,NaN,NaN,NW,37.0,NNW,...,23.0,1023.8,1019.8,NaN,NaN,18.5,23.9,No,0.0,No
95928,2014-08-31,Adelaide,12.3,23.4,0.0,6.0,NaN,N,43.0,NE,...,24.0,1015.9,1010.6,NaN,NaN,17.7,22.3,No,6.8,Yes
95929,2014-09-01,Adelaide,11.3,15.8,6.8,3.0,NaN,WNW,44.0,NaN,...,44.0,1014.1,1014.6,NaN,NaN,11.7,15.5,Yes,5.6,Yes
95930,2014-09-02,Adelaide,6.3,16.2,5.6,2.2,NaN,SW,39.0,SSW,...,60.0,1025.3,1024.9,NaN,NaN,11.9,13.5,Yes,0.4,No
95921,2014-08-24,Adelaide,6.0,16.2,0.0,NaN,NaN,W,26.0,NNW,...,55.0,1031.2,1029.6,NaN,NaN,10.3,15.4,No,0.0,No
95931,2014-09-03,Adelaide,5.6,14.7,0.4,2.4,NaN,N,35.0,NE,...,49.0,1025.1,1020.7,NaN,NaN,10.4,14.6,No,4.8,Yes
95909,2014-08-12,Adelaide,4.5,13.5,0.0,0.8,NaN,SE,35.0,SE,...,39.0,1035.5,1034.1,NaN,NaN,10.0,12.8,No,0.0,No
95907,2014-08-10,Adelaide,6.3,15.2,0.2,NaN,NaN,SSW,33.0,N,...,45.0,1030.8,1029.4,NaN,NaN,11.5,14.1,No,0.4,No
95887,2014-07-21,Adelaide,8.0,16.9,0.0,1.8,NaN,N,24.0,NE,...,41.0,1023.1,1020.8,NaN,NaN,12.0,15.6,No,0.0,No
95888,2014-07-22,Adelaide,3.7,19.0,0.0,1.4,NaN,N,24.0,NaN,...,32.0,1024.2,1021.1,NaN,NaN,9.6,18.5,No,0.0,No
95889,2014-07-23,Adelaide,9.6,15.8,0.0,2.6,NaN,NE,52.0,NNE,...,51.0,1017.9,1011.5,NaN,NaN,14.7,15.4,No,16.6,Yes
95890,2014-07-24,Adelaide,10.1,15.5,16.6,0.8,NaN,NNE,50.0,NW,...,80.0,1007.4,1008.0,NaN,NaN,11.2,14.0,Yes,1.8,Yes
95891,2014-07-25,Adelaide,11.2,16.2,1.8,0.6,NaN,NW,30.0,WNW,...,70.0,1018.4,1019.2,NaN,NaN,13.0,15.3,Yes,3.0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104183,2012-05-27,Woomera,11.1,16.3,0.6,NaN,NaN,SSE,37.0,SSE,...,48.0,1028.2,1027.1,3.0,5.0,12.6,15.4,No,0.0,No
104184,2012-05-28,Woomera,5.6,16.4,0.0,5.2,NaN,SSE,31.0,SE,...,43.0,1033.1,1029.9,0.0,0.0,9.3,15.5,No,0.0,No
104185,2012-05-29,Woomera,5.0,17.2,0.0,3.6,10.1,SE,31.0,SE,...,38.0,1032.6,1030.5,0.0,0.0,10.2,16.6,No,0.0,No
104186,2012-05-30,Woomera,5.8,19.2,0.0,3.8,6.8,ESE,31.0,ESE,...,32.0,1031.8,1028.2,0.0,0.0,10.2,18.5,No,2.4,Yes
104187,2012-05-31,Woomera,8.4,19.5,2.4,5.2,2.2,ESE,26.0,SE,...,53.0,1027.4,1023.3,7.0,3.0,11.9,18.5,Yes,5.0,Yes
104188,2012-06-01,Woomera,11.8,17.4,5.0,1.2,1.8,ESE,30.0,SSE,...,73.0,1024.0,1021.0,5.0,6.0,14.4,17.1,Yes,0.2,No
104171,2012-05-15,Woomera,6.0,20.1,0.0,4.0,10.4,SE,28.0,E,...,27.0,1029.5,1026.0,0.0,0.0,11.3,19.7,No,0.0,No
104170,2012-05-14,Woomera,8.0,18.7,0.0,14.6,NaN,SE,28.0,SE,...,34.0,1030.2,1027.4,0.0,0.0,13.0,18.4,No,0.0,No
104169,2012-05-13,Woomera,6.2,18.0,0.0,NaN,NaN,SSW,33.0,SSE,...,33.0,1028.5,1025.9,NaN,NaN,12.0,17.6,No,0.0,No
104168,2012-05-12,Woomera,9.2,18.6,0.0,NaN,NaN,S,35.0,S,...,33.0,1025.4,1023.0,NaN,7.0,13.7,17.8,No,0.0,No
104150,2012-04-24,Woomera,7.6,20.4,0.0,5.6,8.3,S,39.0,S,...,31.0,1024.0,1022.2,0.0,1.0,12.6,19.1,No,0.0,No
104151,2012-04-25,Woomera,7.3,20.1,0.0,7.0,11.1,S,39.0,S,...,41.0,1026.9,1023.6,0.0,5.0,13.7,19.0,No,0.0,No
104152,2012-04-26,Woomera,9.9,21.6,0.0,3.2,NaN,SW,30.0,SSE,...,36.0,1026.4,1022.6,0.0,1.0,15.3,21.0,No,0.0,No
104153,2012-04-27,Woomera,10.8,22.6,0.0,NaN,NaN,SE,31.0,SE,...,34.0,1024.5,1021.3,NaN,3.0,16.7,21.5,No,0.0,No
104154,2012-04-28,Woomera,9.6,23.5,0.0,NaN,NaN,SE,33.0,SE,...,25.0,1023.8,1020.8,NaN,NaN,15.7,23.4,No,0.0,No
104155,2012-04-29,Woomera,11.7,25.0,0.0,18.0,NaN,ENE,37.0,E,...,26.0,1024.2,1020.8,5.0,5.0,16.2,24.5,No,0.0,No
104156,2012-04-30,Woomera,12.5,26.2,0.0,6.8,NaN,NNE,43.0,NE,...,17.0,1021.1,1016.1,5.0,2.0,18.5,25.5,No,0.0,No
104157,2012-05-01,Woomera,12.8,28.3,0.0,10.4,10.5,S,54.0,N,...,27.0,1019.3,1017.7,3.0,3.0,19.7,25.9,No,0.0,No
104190,2012-06-03,Woomera,8.5,16.9,0.0,3.2,6.1,SSE,43.0,S,...,40.0,1022.0,1018.8,0.0,3.0,10.7,15.6,No,0.0,No
104158,2012-05-02,Woomera,10.6,19.3,0.0,8.0,10.6,SSE,52.0,SSE,...,26.0,1027.1,1025.1,0.0,0.0,14.3,18.7,No,0.0,No
104160,2012-05-04,Woomera,6.2,19.9,0.0,NaN,NaN,ESE,24.0,ESE,...,23.0,1027.0,1023.2,NaN,NaN,12.7,19.5,No,0.0,No
104161,2012-05-05,Woomera,7.0,21.8,0.0,NaN,NaN,NE,30.0,E,...,24.0,1024.0,1019.6,NaN,NaN,14.1,20.5,No,0.0,No
104162,2012-05-06,Woomera,9.0,21.6,0.0,14.4,9.1,N,37.0,NNE,...,24.0,1019.4,1015.8,5.0,5.0,14.1,20.8,No,0.0,No
104163,2012-05-07,Woomera,14.0,28.4,0.0,7.2,3.0,N,46.0,N,...,10.0,1016.0,1012.3,2.0,1.0,18.6,27.6,No,0.0,No
104164,2012-05-08,Woomera,13.4,30.8,0.0,11.2,10.1,NNW,54.0,N,...,8.0,1014.8,1011.4,1.0,0.0,19.2,30.0,No,0.0,No
104165,2012-05-09,Woomera,13.1,25.3,0.0,15.4,9.2,SSE,35.0,S,...,32.0,1019.7,1018.0,4.0,1.0,18.0,24.7,No,0.2,No
104166,2012-05-10,Woomera,13.4,25.1,0.2,7.0,7.9,SE,48.0,S,...,29.0,1022.2,1019.1,3.0,1.0,15.6,24.3,No,0.0,No
104167,2012-05-11,Woomera,10.8,22.3,0.0,5.8,NaN,S,41.0,S,...,34.0,1023.8,1021.3,0.0,NaN,15.8,21.4,No,0.0,No
104159,2012-05-03,Woomera,7.1,17.7,0.0,6.2,NaN,SE,35.0,SE,...,26.0,1028.1,1023.7,0.0,0.0,11.7,17.0,No,0.0,No
105809,2017-01-17,Woomera,22.7,43.5,0.0,NaN,NaN,N,41.0,ENE,...,7.0,1008.5,1005.5,NaN,NaN,31.2,41.8,No,0.0,No

In [18]:
weather.iloc[5]

Date             2008-12-06
Location             Albury
MinTemp                14.6
MaxTemp                29.7
Rainfall                0.2
Evaporation             NaN
Sunshine                NaN
WindGustDir             WNW
WindGustSpeed            56
WindDir9am                W
WindDir3pm                W
WindSpeed9am             19
WindSpeed3pm             24
Humidity9am              55
Humidity3pm              23
Pressure9am          1009.2
Pressure3pm          1005.4
Cloud9am                NaN
Cloud3pm                NaN
Temp9am                20.6
Temp3pm                28.9
RainToday                No
RISK_MM                   0
RainTomorrow             No
Name: 5, dtype: object

In [19]:
weather[0:3]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No

In [20]:
weather.loc[:,["Date","Location"]]

              Date Location
0       2008-12-01   Albury
1       2008-12-02   Albury
2       2008-12-03   Albury
3       2008-12-04   Albury
4       2008-12-05   Albury
5       2008-12-06   Albury
6       2008-12-07   Albury
7       2008-12-08   Albury
8       2008-12-09   Albury
9       2008-12-10   Albury
10      2008-12-11   Albury
11      2008-12-12   Albury
12      2008-12-13   Albury
13      2008-12-14   Albury
14      2008-12-16   Albury
15      2008-12-17   Albury
16      2008-12-18   Albury
17      2008-12-19   Albury
18      2008-12-20   Albury
19      2008-12-21   Albury
20      2008-12-22   Albury
21      2008-12-23   Albury
22      2008-12-24   Albury
23      2008-12-25   Albury
24      2008-12-26   Albury
25      2008-12-27   Albury
26      2008-12-28   Albury
27      2008-12-29   Albury
28      2008-12-30   Albury
29      2008-12-31   Albury
...            ...      ...
142163  2017-05-26    Uluru
142164  2017-05-27    Uluru
142165  2017-05-28    Uluru
142166  2017-05-29    Uluru
142167  2017-05-30    Uluru
142168  2017-05-31    Uluru
142169  2017-06-01    Uluru
142170  2017-06-02    Uluru
142171  2017-06-03    Uluru
142172  2017-06-04    Uluru
142173  2017-06-05    Uluru
142174  2017-06-06    Uluru
142175  2017-06-07    Uluru
142176  2017-06-08    Uluru
142177  2017-06-09    Uluru
142178  2017-06-10    Uluru
142179  2017-06-11    Uluru
142180  2017-06-12    Uluru
142181  2017-06-13    Uluru
142182  2017-06-14    Uluru
142183  2017-06-15    Uluru
142184  2017-06-16    Uluru
142185  2017-06-17    Uluru
142186  2017-06-18    Uluru
142187  2017-06-19    Uluru
142188  2017-06-20    Uluru
142189  2017-06-21    Uluru
142190  2017-06-22    Uluru
142191  2017-06-23    Uluru
142192  2017-06-24    Uluru

[142193 rows x 2 columns]

In [22]:
weather.iloc[:3,:]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No

In [23]:
weather.iloc[:,:3]

              Date Location  MinTemp
0       2008-12-01   Albury     13.4
1       2008-12-02   Albury      7.4
2       2008-12-03   Albury     12.9
3       2008-12-04   Albury      9.2
4       2008-12-05   Albury     17.5
5       2008-12-06   Albury     14.6
6       2008-12-07   Albury     14.3
7       2008-12-08   Albury      7.7
8       2008-12-09   Albury      9.7
9       2008-12-10   Albury     13.1
10      2008-12-11   Albury     13.4
11      2008-12-12   Albury     15.9
12      2008-12-13   Albury     15.9
13      2008-12-14   Albury     12.6
14      2008-12-16   Albury      9.8
15      2008-12-17   Albury     14.1
16      2008-12-18   Albury     13.5
17      2008-12-19   Albury     11.2
18      2008-12-20   Albury      9.8
19      2008-12-21   Albury     11.5
20      2008-12-22   Albury     17.1
21      2008-12-23   Albury     20.5
22      2008-12-24   Albury     15.3
23      2008-12-25   Albury     12.6
24      2008-12-26   Albury     16.2
25      2008-12-27   Albury     16.9
26      2008-12-28   Albury     20.1
27      2008-12-29   Albury     19.7
28      2008-12-30   Albury     12.5
29      2008-12-31   Albury     12.0
...            ...      ...      ...
142163  2017-05-26    Uluru     14.3
142164  2017-05-27    Uluru      9.3
142165  2017-05-28    Uluru      8.0
142166  2017-05-29    Uluru     12.7
142167  2017-05-30    Uluru      9.4
142168  2017-05-31    Uluru      5.4
142169  2017-06-01    Uluru      5.6
142170  2017-06-02    Uluru      1.5
142171  2017-06-03    Uluru      3.8
142172  2017-06-04    Uluru      4.5
142173  2017-06-05    Uluru      4.9
142174  2017-06-06    Uluru      1.2
142175  2017-06-07    Uluru      0.5
142176  2017-06-08    Uluru      4.0
142177  2017-06-09    Uluru      3.4
142178  2017-06-10    Uluru      3.2
142179  2017-06-11    Uluru      2.4
142180  2017-06-12    Uluru      5.1
142181  2017-06-13    Uluru      2.5
142182  2017-06-14    Uluru      2.3
142183  2017-06-15    Uluru      2.6
142184  2017-06-16    Uluru      5.2
142185  2017-06-17    Uluru      6.4
142186  2017-06-18    Uluru      8.0
142187  2017-06-19    Uluru      7.4
142188  2017-06-20    Uluru      3.5
142189  2017-06-21    Uluru      2.8
142190  2017-06-22    Uluru      3.6
142191  2017-06-23    Uluru      5.4
142192  2017-06-24    Uluru      7.8

[142193 rows x 3 columns]

In [24]:
weather.iloc[:2,:5]

         Date Location  MinTemp  MaxTemp  Rainfall
0  2008-12-01   Albury     13.4     22.9       0.6
1  2008-12-02   Albury      7.4     25.1       0.0

In [25]:
weather.iloc[3:5,0:2]

         Date Location
3  2008-12-04   Albury
4  2008-12-05   Albury

In [26]:
weather.iloc[[1,2,4],[0,2]]

         Date  MinTemp
1  2008-12-02      7.4
2  2008-12-03     12.9
4  2008-12-05     17.5

In [27]:
weather.iloc[1:3,:]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No

In [28]:
weather.iloc[:,1:3]

       Location  MinTemp
0        Albury     13.4
1        Albury      7.4
2        Albury     12.9
3        Albury      9.2
4        Albury     17.5
5        Albury     14.6
6        Albury     14.3
7        Albury      7.7
8        Albury      9.7
9        Albury     13.1
10       Albury     13.4
11       Albury     15.9
12       Albury     15.9
13       Albury     12.6
14       Albury      9.8
15       Albury     14.1
16       Albury     13.5
17       Albury     11.2
18       Albury      9.8
19       Albury     11.5
20       Albury     17.1
21       Albury     20.5
22       Albury     15.3
23       Albury     12.6
24       Albury     16.2
25       Albury     16.9
26       Albury     20.1
27       Albury     19.7
28       Albury     12.5
29       Albury     12.0
...         ...      ...
142163    Uluru     14.3
142164    Uluru      9.3
142165    Uluru      8.0
142166    Uluru     12.7
142167    Uluru      9.4
142168    Uluru      5.4
142169    Uluru      5.6
142170    Uluru      1.5
142171    Uluru      3.8
142172    Uluru      4.5
142173    Uluru      4.9
142174    Uluru      1.2
142175    Uluru      0.5
142176    Uluru      4.0
142177    Uluru      3.4
142178    Uluru      3.2
142179    Uluru      2.4
142180    Uluru      5.1
142181    Uluru      2.5
142182    Uluru      2.3
142183    Uluru      2.6
142184    Uluru      5.2
142185    Uluru      6.4
142186    Uluru      8.0
142187    Uluru      7.4
142188    Uluru      3.5
142189    Uluru      2.8
142190    Uluru      3.6
142191    Uluru      5.4
142192    Uluru      7.8

[142193 rows x 2 columns]

In [29]:
weather.iloc[1,1]

'Albury'

In [30]:
weather['Date'].iloc[5]

'2008-12-06'

In [36]:
cols_2_4=weather.columns[2:4]

In [37]:
weather[cols_2_4]

        MinTemp  MaxTemp
0          13.4     22.9
1           7.4     25.1
2          12.9     25.7
3           9.2     28.0
4          17.5     32.3
5          14.6     29.7
6          14.3     25.0
7           7.7     26.7
8           9.7     31.9
9          13.1     30.1
10         13.4     30.4
11         15.9     21.7
12         15.9     18.6
13         12.6     21.0
14          9.8     27.7
15         14.1     20.9
16         13.5     22.9
17         11.2     22.5
18          9.8     25.6
19         11.5     29.3
20         17.1     33.0
21         20.5     31.8
22         15.3     30.9
23         12.6     32.4
24         16.2     33.9
25         16.9     33.0
26         20.1     32.7
27         19.7     27.2
28         12.5     24.2
29         12.0     24.4
...         ...      ...
142163     14.3     27.6
142164      9.3     28.0
142165      8.0     24.6
142166     12.7     22.2
142167      9.4     22.7
142168      5.4     20.5
142169      5.6     19.4
142170      1.5     19.2
142171      3.8     19.8
142172      4.5     18.8
142173      4.9     20.7
142174      1.2     20.8
142175      0.5     21.7
142176      4.0     20.0
142177      3.4     19.8
142178      3.2     18.6
142179      2.4     19.1
142180      5.1     19.7
142181      2.5     21.2
142182      2.3     21.4
142183      2.6     22.5
142184      5.2     24.3
142185      6.4     23.4
142186      8.0     20.7
142187      7.4     20.6
142188      3.5     21.8
142189      2.8     23.4
142190      3.6     25.3
142191      5.4     26.9
142192      7.8     27.0

[142193 rows x 2 columns]

In [38]:
weather[weather.columns[2:4]].iloc[5:10]

   MinTemp  MaxTemp
5     14.6     29.7
6     14.3     25.0
7      7.7     26.7
8      9.7     31.9
9     13.1     30.1

In [39]:
weather.isnull

<bound method DataFrame.isnull of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN
1       2008-12-02   Albury      7.4     25.1       0.0          NaN
2       2008-12-03   Albury     12.9     25.7       0.0          NaN
3       2008-12-04   Albury      9.2     28.0       0.0          NaN
4       2008-12-05   Albury     17.5     32.3       1.0          NaN
5       2008-12-06   Albury     14.6     29.7       0.2          NaN
6       2008-12-07   Albury     14.3     25.0       0.0          NaN
7       2008-12-08   Albury      7.7     26.7       0.0          NaN
8       2008-12-09   Albury      9.7     31.9       0.0          NaN
9       2008-12-10   Albury     13.1     30.1       1.4          NaN
10      2008-12-11   Albury     13.4     30.4       0.0          NaN
11      2008-12-12   Albury     15.9     21.7       2.2          NaN
12      2008-12-13   Albury     15.9     18.6      15.6          NaN
13      2008-12-14   Albury     12.6     21.0       3.6          NaN
14      2008-12-16   Albury      9.8     27.7       NaN          NaN
15      2008-12-17   Albury     14.1     20.9       0.0          NaN
16      2008-12-18   Albury     13.5     22.9      16.8          NaN
17      2008-12-19   Albury     11.2     22.5      10.6          NaN
18      2008-12-20   Albury      9.8     25.6       0.0          NaN
19      2008-12-21   Albury     11.5     29.3       0.0          NaN
20      2008-12-22   Albury     17.1     33.0       0.0          NaN
21      2008-12-23   Albury     20.5     31.8       0.0          NaN
22      2008-12-24   Albury     15.3     30.9       0.0          NaN
23      2008-12-25   Albury     12.6     32.4       0.0          NaN
24      2008-12-26   Albury     16.2     33.9       0.0          NaN
25      2008-12-27   Albury     16.9     33.0       0.0          NaN
26      2008-12-28   Albury     20.1     32.7       0.0          NaN
27      2008-12-29   Albury     19.7     27.2       0.0          NaN
28      2008-12-30   Albury     12.5     24.2       1.2          NaN
29      2008-12-31   Albury     12.0     24.4       0.8          NaN
...            ...      ...      ...      ...       ...          ...
142163  2017-05-26    Uluru     14.3     27.6       0.4          NaN
142164  2017-05-27    Uluru      9.3     28.0       0.0          NaN
142165  2017-05-28    Uluru      8.0     24.6       0.0          NaN
142166  2017-05-29    Uluru     12.7     22.2       0.0          NaN
142167  2017-05-30    Uluru      9.4     22.7       0.0          NaN
142168  2017-05-31    Uluru      5.4     20.5       0.0          NaN
142169  2017-06-01    Uluru      5.6     19.4       0.0          NaN
142170  2017-06-02    Uluru      1.5     19.2       0.0          NaN
142171  2017-06-03    Uluru      3.8     19.8       0.0          NaN
142172  2017-06-04    Uluru      4.5     18.8       0.0          NaN
142173  2017-06-05    Uluru      4.9     20.7       0.0          NaN
142174  2017-06-06    Uluru      1.2     20.8       0.0          NaN
142175  2017-06-07    Uluru      0.5     21.7       0.0          NaN
142176  2017-06-08    Uluru      4.0     20.0       0.0          NaN
142177  2017-06-09    Uluru      3.4     19.8       0.0          NaN
142178  2017-06-10    Uluru      3.2     18.6       0.0          NaN
142179  2017-06-11    Uluru      2.4     19.1       0.0          NaN
142180  2017-06-12    Uluru      5.1     19.7       0.0          NaN
142181  2017-06-13    Uluru      2.5     21.2       0.0          NaN
142182  2017-06-14    Uluru      2.3     21.4       0.0          NaN
142183  2017-06-15    Uluru      2.6     22.5       0.0          NaN
142184  2017-06-16    Uluru      5.2     24.3       0.0          NaN
142185  2017-06-17    Uluru      6.4     23.4       0.0          NaN
142186  2017-06-18    Uluru      8.0     20.7       0.0          NaN
142187  2017-06-19    Uluru      7.4     20.6       0.0          NaN
142188  2017-06-20    Uluru      3.5     21.8       0.0          NaN
142189  2017-06-21    Uluru      2.8     23.4       0.0          NaN
142190  2017-06-22    Uluru      3.6     25.3       0.0          NaN
142191  2017-06-23    Uluru      5.4     26.9       0.0          NaN
142192  2017-06-24    Uluru      7.8     27.0       0.0          NaN

        Sunshine WindGustDir  WindGustSpeed WindDir9am      ...       \
0            NaN           W           44.0          W      ...
1            NaN         WNW           44.0        NNW      ...
2            NaN         WSW           46.0          W      ...
3            NaN          NE           24.0         SE      ...
4            NaN           W           41.0        ENE      ...
5            NaN         WNW           56.0          W      ...
6            NaN           W           50.0         SW      ...
7            NaN           W           35.0        SSE      ...
8            NaN         NNW           80.0         SE      ...
9            NaN           W           28.0          S      ...
10           NaN           N           30.0        SSE      ...
11           NaN         NNE           31.0         NE      ...
12           NaN           W           61.0        NNW      ...
13           NaN          SW           44.0          W      ...
14           NaN         WNW           50.0        NaN      ...
15           NaN         ENE           22.0        SSW      ...
16           NaN           W           63.0          N      ...
17           NaN         SSE           43.0        WSW      ...
18           NaN         SSE           26.0         SE      ...
19           NaN           S           24.0         SE      ...
20           NaN          NE           43.0         NE      ...
21           NaN         WNW           41.0          W      ...
22           NaN           N           33.0        ESE      ...
23           NaN           W           43.0          E      ...
24           NaN         WSW           35.0         SE      ...
25           NaN         WSW           57.0        NaN      ...
26           NaN         WNW           48.0          N      ...
27           NaN         WNW           46.0         NW      ...
28           NaN         WNW           50.0        WSW      ...
29           NaN           W           39.0        WNW      ...
...          ...         ...            ...        ...      ...
142163       NaN         WNW           39.0        NaN      ...
142164       NaN           W           28.0        SSW      ...
142165       NaN           E           33.0         SE      ...
142166       NaN           E           37.0          E      ...
142167       NaN           E           35.0         SE      ...
142168       NaN           E           46.0          E      ...
142169       NaN           E           43.0          E      ...
142170       NaN           E           37.0        ESE      ...
142171       NaN         ENE           39.0        ESE      ...
142172       NaN           E           31.0        ESE      ...
142173       NaN           E           37.0        ESE      ...
142174       NaN           E           43.0        ESE      ...
142175       NaN           E           43.0        ESE      ...
142176       NaN          SE           39.0        ESE      ...
142177       NaN           E           43.0        ESE      ...
142178       NaN           E           46.0        ESE      ...
142179       NaN           E           33.0         SE      ...
142180       NaN           E           46.0        ESE      ...
142181       NaN         ENE           35.0        ESE      ...
142182       NaN          SE           22.0         SE      ...
142183       NaN           S           19.0          S      ...
142184       NaN           E           24.0         SE      ...
142185       NaN         ESE           31.0          S      ...
142186       NaN         ESE           41.0         SE      ...
142187       NaN           E           35.0        ESE      ...
142188       NaN           E           31.0        ESE      ...
142189       NaN           E           31.0         SE      ...
142190       NaN         NNW           22.0         SE      ...
142191       NaN           N           37.0         SE      ...
142192       NaN          SE           28.0        SSE      ...

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0             22.0       1007.7       1007.1       8.0       NaN     16.9
1             25.0       1010.6       1007.8       NaN       NaN     17.2
2             30.0       1007.6       1008.7       NaN       2.0     21.0
3             16.0       1017.6       1012.8       NaN       NaN     18.1
4             33.0       1010.8       1006.0       7.0       8.0     17.8
5             23.0       1009.2       1005.4       NaN       NaN     20.6
6             19.0       1009.6       1008.2       1.0       NaN     18.1
7             19.0       1013.4       1010.1       NaN       NaN     16.3
8              9.0       1008.9       1003.6       NaN       NaN     18.3
9             27.0       1007.0       1005.7       NaN       NaN     20.1
10            22.0       1011.8       1008.7       NaN       NaN     20.4
11            91.0       1010.5       1004.2       8.0       8.0     15.9
12            93.0        994.3        993.0       8.0       8.0     17.4
13            43.0       1001.2       1001.8       NaN       7.0     15.8
14            28.0       1013.4       1010.3       0.0       NaN     17.3
15            82.0       1012.2       1010.4       8.0       1.0     17.2
16            65.0       1005.8       1002.2       8.0       1.0     18.0
17            32.0       1009.4       1009.7       NaN       2.0     15.5
18            26.0       1019.2       1017.1       NaN       NaN     15.8
19            28.0       1019.3       1014.8       NaN       NaN     19.1
20            28.0       1013.6       1008.1       NaN       1.0     24.5
21            24.0       1007.8       1005.7       NaN       NaN     23.8
22            23.0       1011.0       1008.2       5.0       NaN     20.9
23            17.0       1012.9       1010.1       NaN       NaN     21.5
24            19.0       1010.9       1007.6       NaN       1.0     23.2
25            28.0       1006.8       1003.6       NaN       1.0     26.6
26            15.0       1005.2       1001.7       NaN       NaN     24.6
27            22.0       1004.8       1004.2       NaN       NaN     21.6
28            70.0       1005.6       1003.4       8.0       8.0     12.5
29            28.0       1006.1       1005.1       1.0       NaN     16.9
...            ...          ...          ...       ...       ...      ...
142163        27.0       1020.5       1016.1       4.0       7.0     16.1
142164        16.0       1019.9       1016.9       NaN       NaN     16.6
142165        25.0       1021.7       1018.8       4.0       NaN     13.8
142166        34.0       1024.3       1021.7       8.0       8.0     13.9
142167        32.0       1026.6       1023.6       8.0       4.0     11.8
142168        32.0       1029.2       1025.3       NaN       NaN     11.1
142169        22.0       1029.6       1027.1       NaN       NaN      9.7
142170        18.0       1030.7       1026.7       NaN       NaN      6.8
142171        22.0       1028.7       1024.1       NaN       NaN      8.6
142172        26.0       1026.9       1022.4       NaN       NaN      9.5
142173        11.0       1027.1       1023.9       NaN       NaN     10.3
142174         6.0       1029.8       1025.9       NaN       NaN      7.9
142175        19.0       1029.0       1025.0       NaN       NaN      9.5
142176        26.0       1030.2       1026.7       NaN       NaN      9.1
142177        23.0       1031.8       1027.7       NaN       NaN      8.7
142178        29.0       1031.0       1027.2       NaN       NaN      8.2
142179        24.0       1030.0       1026.2       NaN       NaN      8.0
142180        29.0       1028.5       1025.8       NaN       NaN      8.5
142181        32.0       1027.2       1023.0       NaN       NaN     10.3
142182        28.0       1026.9       1022.8       NaN       NaN      8.9
142183        24.0       1025.0       1021.4       NaN       NaN      8.8
142184        24.0       1023.8       1020.0       NaN       NaN     12.3
142185        25.0       1025.8       1023.0       NaN       NaN     11.2
142186        32.0       1028.1       1024.3       NaN       7.0     11.6
142187        33.0       1027.2       1023.3       NaN       NaN     11.0
142188        27.0       1024.7       1021.2       NaN       NaN      9.4
142189        24.0       1024.6       1020.3       NaN       NaN     10.1
142190        21.0       1023.5       1019.1       NaN       NaN     10.9
142191        24.0       1021.0       1016.8       NaN       NaN     12.5
142192        24.0       1019.4       1016.5       3.0       2.0     15.1

        Temp3pm  RainToday  RISK_MM  RainTomorrow
0          21.8         No      0.0            No
1          24.3         No      0.0            No
2          23.2         No      0.0            No
3          26.5         No      1.0            No
4          29.7         No      0.2            No
5          28.9         No      0.0            No
6          24.6         No      0.0            No
7          25.5         No      0.0            No
8          30.2         No      1.4           Yes
9          28.2        Yes      0.0            No
10         28.8         No      2.2           Yes
11         17.0        Yes     15.6           Yes
12         15.8        Yes      3.6           Yes
13         19.8        Yes      0.0            No
14         26.2        NaN      0.0            No
15         18.1         No     16.8           Yes
16         21.5        Yes     10.6           Yes
17         21.0        Yes      0.0            No
18         23.2         No      0.0            No
19         27.3         No      0.0            No
20         31.6         No      0.0            No
21         30.8         No      0.0            No
22         29.0         No      0.0            No
23         31.2         No      0.0            No
24         33.0         No      0.0            No
25         31.2         No      0.0            No
26         32.1         No      0.0            No
27         26.1         No      1.2           Yes
28         18.2        Yes      0.8            No
29         22.7         No      0.0            No
...         ...        ...      ...           ...
142163     27.2         No      0.0            No
142164     27.3         No      0.0            No
142165     23.5         No      0.0            No
142166     21.0         No      0.0            No
142167     22.3         No      0.0            No
142168     20.2         No      0.0            No
142169     18.3         No      0.0            No
142170     17.6         No      0.0            No
142171     18.9         No      0.0            No
142172     18.6         No      0.0            No
142173     19.8         No      0.0            No
142174     19.9         No      0.0            No
142175     20.5         No      0.0            No
142176     19.0         No      0.0            No
142177     18.9         No      0.0            No
142178     17.4         No      0.0            No
142179     18.8         No      0.0            No
142180     19.2         No      0.0            No
142181     20.3         No      0.0            No
142182     20.3         No      0.0            No
142183     22.1         No      0.0            No
142184     23.3         No      0.0            No
142185     23.1         No      0.0            No
142186     20.0         No      0.0            No
142187     20.3         No      0.0            No
142188     20.9         No      0.0            No
142189     22.4         No      0.0            No
142190     24.5         No      0.0            No
142191     26.1         No      0.0            No
142192     26.0         No      0.0            No

[142193 rows x 24 columns]>

In [40]:
weather.isnull().any()

Date             False
Location         False
MinTemp           True
MaxTemp           True
Rainfall          True
Evaporation       True
Sunshine          True
WindGustDir       True
WindGustSpeed     True
WindDir9am        True
WindDir3pm        True
WindSpeed9am      True
WindSpeed3pm      True
Humidity9am       True
Humidity3pm       True
Pressure9am       True
Pressure3pm       True
Cloud9am          True
Cloud3pm          True
Temp9am           True
Temp3pm           True
RainToday         True
RISK_MM          False
RainTomorrow     False
dtype: bool

In [41]:
weather.isnull().sum().sum()

316559L

In [42]:
weather.isnull().sum(axis = 1)

0         3
1         4
2         3
3         4
4         2
5         4
6         3
7         4
8         4
9         4
10        4
11        2
12        2
13        3
14        7
15        2
16        2
17        3
18        4
19        4
20        3
21        4
22        3
23        4
24        3
25        4
26        4
27        4
28        2
29        3
         ..
142163    3
142164    4
142165    3
142166    2
142167    2
142168    4
142169    4
142170    4
142171    4
142172    4
142173    4
142174    4
142175    4
142176    4
142177    4
142178    4
142179    4
142180    4
142181    4
142182    4
142183    4
142184    4
142185    4
142186    3
142187    4
142188    4
142189    4
142190    4
142191    4
142192    2
Length: 142193, dtype: int64

In [47]:
weather.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [48]:
weather['RISK_MM']=weather['RISK_MM'].astype("int")

In [49]:
weather.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM            int64
RainTomorrow      object
dtype: object